name: news
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.3 <4.0.0"

dependencies:
  cached_network_image: ^3.3.0
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  dio: ^5.3.3
  dropdown_search: ^5.0.6
  email_validator: ^2.1.17
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  get_it: ^7.6.4
  go_router: ^11.1.2
  google_fonts: ^5.1.0
  image_picker: ^1.0.2
  intl: ^0.18.1
  provider: ^6.0.5
  shared_preferences: ^2.2.1
  url_launcher: ^6.1.14

dev_dependencies:
  bloc_test: ^9.1.4
  flutter_lints: ^2.0.0
  mocktail: ^1.0.1

  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/